### PR TITLE
Python 3 port

### PR DESCRIPTION
**Pull request by jrs65**
A minimal porting of alpenhorn to support Python 3. Done using python-future (though doesn't need its compatibility library).

### CODE REVIEW

**Comment by cubranic** [comment]
Nice! I’m slightly miffed that we’re stuck with 2.7 for the FRB pipeline. 

Are we trying to be friendly to both 2.7 and 3?

Davor

**Comment by jrs65** [comment]
Yeah. I figured we may as well try and explicitly support Python 3. At the moment for cosmology we're on Python 2.7, but I have a vague plan to try and slowly port everything onto Python 3. The writing is on the wall for 2.7 (new IPython releases will no longer support it).

**Comment by jrs65** [comment]
Also, I think the biggest issue stopping these tests passing is a failure in some code you introduced in `test_client.py`. Any idea what is going on?

**Comment by cubranic** [comment]
Not the slightest, I don’t have any experience with Python 3. My guess would be that the mocking works slightly differently. Or maybe some regex switch, I don’t use much else in those tests.

**Comment by jrs65** [comment]
Ah no. I don't mean that failure (there's one that seems to be a version conflict installing on Python 3.5). I mean the failure for Python 2.7 on the master branch. The same failure also occurs for Python 2.7 on this branch, and Python 3.6 on this branch.

**Comment by cubranic** [comment]
Hm, weird. Passes on my machine. Probably some platform-dependent details of how the order in which directory contents are reported in that “unknown files” output. Let me test that...

**Comment by cubranic** [comment]
Yep. That's what it was. Sigh.

**Comment by jrs65** [comment]
Similarly this one I think is pretty uncontroversial.

**Pull request merged**
