### PR TITLE
fix(pyproject): Find subpackages

### PR DESCRIPTION
**Pull request by ketiltrout**
There's a lot of subpackages now.  And there will be more coming with the client re-write.

### CODE REVIEW

**Review by ljgray — APPROVED** [review]
This is fine, but I think you could just do something like 
```toml
[tool.setuptools.packages]
find = {}
```

like we've done in other repos, which should have the same effect

**Comment by ketiltrout** [comment]
Yeah, thinking about it more, I think that's going to be more maintainable.  Let me change it...

**Comment by ketiltrout** [comment]
Package installation has been broken since at least #185, but I think it might have been broken all the way back in the re-write.  We apparently never directly install it...

**Review by ljgray — APPROVED** [review]
Yeah that's what we've done everywhere else and it seems to have worked

**Pull request merged**
